### ISSUE TITLE
[BUG] Doesn't run on macOS Photoshop v 22.4.2

### ISSUE THREAD

**Issue by kbartlez** [schroef/Photoshop-Scripts#2]
**OS:**
 - OS: OSX

**SCRIPT:**
 - Version: 119

**Describe the bug**
Error message as soon as script is launched. Error started with Photoshop v22.4.0 on macOS.

**To Reproduce**
1. Launch script
2. Error dialog box displays.

**Screenshots**
![Screen Shot 2021-07-01 at 3 55 57 PM](https://user-images.githubusercontent.com/86808390/124199385-9fb7e000-da87-11eb-840f-045632513699.png)

**Comment by schroef** [comment]
Does the file actually have an artboard?

I need to check ps extend code,perhaps they made updates. Would be weird because I believe these naming conventions don't change over version. At least most of the times.

I believe I did had an error catch for this implemented. I'll try to check it asap

Ps this is v119 correct? Because the script only goes up to line 25.. something and the error states 3631?

**Comment by kbartlez** [comment]
Thank you for the reply! Yes, it does have artboards. In fact, the script was working fine on the file prior to the latest version of Photoshop. The script is indeed v119. On a lark, I re-downloaded and re-installed the script. I get the same error but referencing a different non-existing line of code, it would appear.

![Screen Shot 2021-07-06 at 10 55 16 AM](https://user-images.githubusercontent.com/86808390/124645765-ad36e680-de48-11eb-8cf7-8b058e6c975b.png)

**Comment by schroef** [comment]
Would it be possible you share that file. You can strip it of most content, just place text frames or so with artboard names.
Could perhaps also test if this works when the artboard is selected. It should give an alert stating ```true```

save this code as isArtboard.jsx
```
function isArtboard(){
    var ref = new ActionReference();
    ref.putEnumerated( charIDToTypeID( "Lyr " ), charIDToTypeID( "Ordn" ), charIDToTypeID( "Trgt" ) );
    var isArtboardLayer = executeActionGet(ref).getBoolean(stringIDToTypeID("artboardEnabled"));
    alert(isArtboardLayer)
    // $.writeln(isArtboardLayer);

}
isArtboard()
```

Then run the script from File > Scripts > Browse. Then selected the file you saved from the code above.
I tried the script again with some test documents i got with both layer comps and artboards and it runs fine for me in v22.0.0 on windows 10 and also on osx 10.11.7 (yeah a bit old)

**Comment by schroef** [comment]
Well im not sure what happened, but i also now see very strange behavior on OSX. I have 2018 cc at the office at it does run but it goes beserk with cropping, i get like 39k pixel width exports?!?! 

I need to fall back to v18 or earlier and see what happened there. Its kinda weird, it was working i would have noticed this behaviour because its one of the core features of the script. This is really weird.
It was working on OSX on one point and then i went on adding more options and mainly developing the script on Windows.

**Comment by schroef** [comment]
I found the issue why flattened files didnt work no more. While i was pinpointing the issue with exporting layered files like PSD and TIFF i turned off some feature to make sure those parts were working.

For me on OSX PS 2018 v19 it works flawless. On my Windows machine running 2021 22.4.0 its okay. I find Photoshop lagging insanely on Windows. Ive run some speed tests and the same export is about 5.4 seconds on OSX where it takes windows about 56.3 seconds. Thats difference is just INSANE.

i was hoping PS v22.40 would fix that lag, but its still there. Photoshop becomes non-responsive for a couple seconds now and then. I also see a sort of loading circle a lot on Windows. Where asin PS on OSX it blasts through the export.

Ill upload the new version later tonight, hope it also works on your side.

**Comment by schroef** [comment]
Ive uploaded a new version, i believe most items should work now 

[latest release](https://github.com/schroef/photoshop-scripts/releases/latest)

**Comment by kbartlez** [comment]
Sadly, I'm still getting the same error even after replacing the script with v20. I tried it on a different file just to see if my source file was bad, but still getting the error.

**Comment by schroef** [comment]
Could you perhaps share that file in a stripped version. So keep the artboards and keep the layercomps. Just add something like textframe with say layercomp name or artboard name

**Comment by kbartlez** [comment]
[ARTBOARD_Example.psd.zip](https://github.com/schroef/Photoshop-Scripts/files/6803433/ARTBOARD_Example.psd.zip)

Attached is a stripped down sample file. I've verified that even at this state, the issue still exists. Thank you.

**Comment by schroef** [comment]
@kbartlez thanks will try asap and how it runs in my versions

**Comment by schroef** [comment]
Ive added an extra check to see if artboards are enabled before the dialog runs. For me it now works and runs fine with your file.

Could you test the [v1.2.1 release](https://github.com/schroef/Photoshop-Scripts/releases)?

**Comment by kbartlez** [comment]
HUZZAH! That worked!

**Comment by schroef** [comment]
Great man! Hope it runs fast as well. Still not sure why it takes so long in the windows version of Photoshop. Photoshop at work blazes through a file in 6-7 seconds, at home this same file takes 56-57 seconds.

**Comment by kbartlez** [comment]
Could it be PNGs? I know PNG exports take WAY longer thank JPG.

Thank you again. This script makes localizing all the online banners I do SO MUCH easier.

**Comment by schroef** [comment]
@kbartlez , nice! glad it helps.

Yeah i guess the existing method layercomps wont help much. I believe you need to do it manually artboard by artboard, right?

Its not the export of PNG, i know that can take more time when transparent. Its just the GUI of Photoshop lags on my Windows system. I also notice it when i use it. It literally gets unresponsive. When its running a script, i see this loading circle lots of times. Where the OSX version blazes through it.
